version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: Generates Go proto files in /sso
    cmds:
      - protoc -I proto/proto  --go-grpc_out=proto/gen proto/proto/sso.proto  --go_out=proto/gen proto/proto/sso.proto --go-grpc_opt=paths=source_relative --go_opt=paths=source_relative